version: "3.7"

services: 

    redis:
        image: redis
        ports: 
            - "6379:6379"
        
    flask:
        image: flask
        build: .
        command: "bash entrypoint.sh"
        restart: always
        depends_on: 
            - redis
        ports: 
            - "5000:5000"
        volumes: 
            - ./:/flask
        env_file: 
            - environment.env

    worker:
        image: flask
        build: .
        command: "celery worker -A app.celery --loglevel=info"
        restart: always
        depends_on: 
            - redis
        volumes: 
            - ./:/flask
        env_file: 
            - environment.env