"""empty message

Revision ID: 21885269a419
Revises: a45ff63588ea
Create Date: 2020-04-16 23:00:53.765248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21885269a419'
down_revision = 'a45ff63588ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musics', sa.Column('s3_upload', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musics', 's3_upload')
    # ### end Alembic commands ###
