"""empty message

Revision ID: 53de8d2e7c20
Revises: 
Create Date: 2020-04-15 20:08:50.147536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53de8d2e7c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('upload_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musics')
    # ### end Alembic commands ###
