"""empty message

Revision ID: b8cb37f0192a
Revises: 9d0d148f7b50
Create Date: 2020-04-17 22:41:43.652940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cb37f0192a'
down_revision = '9d0d148f7b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musics', sa.Column('s3_upload', sa.Boolean(), nullable=True))
    op.add_column('musics', sa.Column('s3_url', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'musics', 'users', ['user_id'], ['id'])
    op.drop_column('musics', 'upload_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musics', sa.Column('upload_type', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'musics', type_='foreignkey')
    op.drop_column('musics', 's3_url')
    op.drop_column('musics', 's3_upload')
    # ### end Alembic commands ###
